### ISSUE TITLE
Running dogwatch against the example Dogfile results in an Syntax error

### ISSUE THREAD

**Issue by udangel-r7** [rapid7/dogwatch#11]
```
$ /usr/local/bin/dogwatch create --dogfile=Dogfile
/var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/dogfile.rb:19:in `instance_eval': /tmp/Dogfile:10: syntax error, unexpected ':', expecting keyword_end (SyntaxError)
      silenced '*': nil
                   ^
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/dogfile.rb:19:in `create'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/bin/dogwatch:23:in `create'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/bin/dogwatch:28:in `<top (required)>'
    from /usr/local/bin/dogwatch:23:in `load'
    from /usr/local/bin/dogwatch:23:in `<main>'
```

with the following content in `Dogfile`

``` ruby
# $ cat Dogfile
DogWatch.monitor do
  ## Create a new monitor - monitor name is REQUIRED
  monitor 'MONITOR NAME' do
    type :metric_alert # REQUIRED: One of [:metric_alert | :service_check | :event_alert]
    query 'time_aggr(time_window):space_aggr:metric{tags} [by {key}] operator' # REQUIRED
    message 'MESSAGE'
    tags %w(A list of tags to associate with your monitor)

    options do
      silenced '*': nil
      notify_no_data false
      no_data_timeframe 3
      timeout_h 99
      renotify_interval 60
      escalation_message 'oh snap'
      include_tags true
    end
  end
end
```

which is exactly the example provided in the README.md file

**Comment by erran-r7** [comment]
@udangel-r7 What version of Ruby are you running with? Only version v2.2.x+ support the `'key': value` syntax for hashes. I'm not sure if we use that hash syntax elsewhere but if it is used in the actual gem code we should restrict the Ruby versions we can run on. Otherwise we can just use the backwards compatible `'key' => value` syntax.
