### ISSUE TITLE
Can not set notify_no_data

### ISSUE THREAD

**Issue by udangel-r7** [rapid7/dogwatch#12]
With the following `Dogfile`:

```
DogWatch.monitor do
  # Check if restdb is available via haproxy
  monitor "Logentries: restdb available" do
    type :metric_alert
    query "max(last_1m):min:haproxy.backend_hosts{service:servicenamei,available:true} < 1"
    message %Q(service not available via haproxy

Playbook:

* Run `something magic`

Setup via Dogwatch)

    options do
        notify_no_data true
    end
   end
end
```

generates the following exception:

```
/var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/model/options.rb:25:in `render': undefined method `to_h' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/model/monitor.rb:56:in `options'
    from /tmp/Dogfile:17:in `block (2 levels) in create'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/monitor.rb:28:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/monitor.rb:28:in `monitor'
    from /tmp/Dogfile:4:in `block in create'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/monitor.rb:20:in `instance_exec'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/monitor.rb:20:in `initialize'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch.rb:7:in `new'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch.rb:7:in `monitor'
    from /tmp/Dogfile:2:in `create'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/dogfile.rb:19:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/lib/dogwatch/dogfile.rb:19:in `create'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/bin/dogwatch:23:in `create'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /var/lib/gems/1.9.1/gems/dogwatch-1.0.4/bin/dogwatch:28:in `<top (required)>'
    from /usr/local/bin/dogwatch:23:in `load'
    from /usr/local/bin/dogwatch:23:in `<main>'
```

**Comment by erran-r7** [comment]
@udangel-r7 another error due to your version of Ruby. I'll add a restriction stating that 2.2.x+ is required to run dogwatch. `OpenStruct#each_pair` was not defined in Ruby `v1.9.x`.
